spring.application.name=apigateway

Server.port=80

# Eureka Service configuration (Discovery)
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true

# Route: Forward /api-gateway/eurekaservice-1/ to lb://eurekaservice1 using dynamic discovery
spring.cloud.gateway.server.webflux.routes[0].id=eurekaservice-1
spring.cloud.gateway.server.webflux.routes[0].uri=lb://eurekaservice1
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api-gateway/eurekaservice-1/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=RewritePath=/api-gateway/eurekaservice-1/(?<segment>.*), /${segment}

# Route: Forward /api-gateway/eurekaservice-2/ to lb://eurekaservice2 using dynamic discovery
spring.cloud.gateway.server.webflux.routes[1].id=eurekaservice-2
spring.cloud.gateway.server.webflux.routes[1].uri=lb://eurekaservice2
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api-gateway/eurekaservice-2/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=RewritePath=/api-gateway/eurekaservice-2/(?<segment>.*), /${segment}