spring.application.name=eurekaservice1

server.port=8081

#Eureka Service Cofiguration (Discovery)
eureka.Client.register-with-eureka=true
eureka.Client.fetch-registry=true
eureka.Client.serviceUrl.defaultZone=http:localhost:8761/eureka
eureka.instance.hostname=localhost
