spring.application.name=eurekaservice2

server.port=8082

#Eureka Service configuration (Discovery)
eureka.client.register-with-eureka=true
eureka.client.fetch-registryUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost

